### ISSUE TITLE
HttpClient does not allow Body Content on full .NET Framework

### ISSUE THREAD

**Issue by cybernami** [fuzzzerd/fmdata#126]
Wanted to let you know that HttpClient in Framework is different than in Core [https://github.com/dotnet/core/issues/1333](url) 
HttpClient in Framework does not allow Body Content which would make your SendAsync_EmptyFind_ShouldReturnMany unit Test fail if run in Framework

There is no way to get all records from FMData in NET Framework at the moment... But it works in Core

**Comment by fuzzzerd** [comment]
@cybernami after reading that thread, it appears the full framework workaround is to use a different handler for HttpClient, and FMData will take an injected client. Can you confirm if [this workaround helps your use case](https://github.com/dotnet/corefx/issues/28135#issuecomment-467683972)?

**Comment by cybernami** [comment]
After getting nuget package [https://www.nuget.org/packages/System.Net.Http.WinHttpHandler/](url) and used that handler, it worked
`var client = new HttpClient(WinHttpHandler)`

But i'm not sure if i should consider it a good workaround as i now have a lot of packages in my library like NetCore and NetStandard... Cannot say at the moment if it have bad effect on my project but i do not experience any right now...

**Comment by fuzzzerd** [comment]
If you have a solution that could be implemented in the base FMData package without introducing new dependencies or breaking the .NET Core functionality I'd be open to a pull request. 

Having said that, I think using WinHttpHandler is a reasonable solution for folks on full framework.

**Comment by fuzzzerd** [comment]
I'm closing this issue for now, as WinHttpHandler is the recommended option for Full Framework users.
