### ISSUE TITLE
Support for repetition fields

### ISSUE THREAD

**Issue by bernardmoes** [fuzzzerd/fmdata#172]
Are repetition fields supported? If so how do I get and store repetition field data? I tried to get repetition field data and I haven't succeeded yet using an array, object or any other data type. I can't find anything in the docs about it either. I know the Filemaker API does support repetition fields.

**Comment by fuzzzerd** [comment]
FMData uses json serialization to convert the response from the data api into a C# object. You would need to create a model class that can hydrated from the data api response. I have not worked with repeating fields, so I don't know how they are modeled in the data api, can you share a sample?
