### ISSUE TITLE
Probably unnecessary auth during GetProductInformationAsync() in FileMakerRestClient

### ISSUE THREAD

**Issue by inf13** [fuzzzerd/fmdata#181]
Hello!
Regarding the official documentation it is not needed to pass auth header during productInfo API call.
I'd suggest remove Auth call to reduce the number of API call. 

For instance, in our API we're using this "productInfo" like a health check endpoint and additional auth call is definitely not needed.

Thanks!

**Comment by fuzzzerd** [comment]
To confirm, you are proposing removing this line from the Rest Client?

https://github.com/fuzzzerd/fmdata/blob/3b18d3041d19e8edbf63ae8a9e85844240acc107/src/FMData.Rest/FileMakerRestClient.cs#L775

**Comment by fuzzzerd** [comment]
That seems like a reasonable change, as you noted, [the Claris documentation states no headers are required](https://help.claris.com/en/data-api-guide/#get-metadata_get-product-info) for that endpoint.

If you want to submit a pull request that'd be great. Otherwise I'll add it to the backlog.

**Comment by inf13** [comment]
> If you want to submit a pull request that'd be great. Otherwise I'll add it to the backlog.
Sure, I'll prepare the pull request :)
