### ISSUE TITLE
Update README.MD with information regarding Cloud Support

### ISSUE THREAD

**Issue by fuzzzerd** [fuzzzerd/fmdata#217]
- [x] Update packages table with Nuget/Myget info cards.
- [x] Update package description list.
- [x] Update Example Usage to include a sample for FileMaker Cloud.

Follow-up docs for #213.

**Comment by fuzzzerd** [comment]
@heebinho could you provide a sample of how to use the new Auth library as a comment here? I'd like to include a new section in the readme file.

**Comment by heebinho** [comment]
# FileMaker Cloud

## Setup

First of all you'll have to activate the FileMaker Data API in the FileMaker Cloud Admin Console.
(You can find the link to your Admin Console under: https://console.claris.com/app/hosts)

When you're already there, note the URL of your Host. Most likely it will look something like https://{NAME}.account.filemaker-cloud.com.

![image](https://user-images.githubusercontent.com/1469531/182467588-3c622ad5-6f8e-422e-8617-a9f5c878143f.png)


To access any given database via the Rest API, you'll have to grant special rights to a "Privilege Set" and assign the set to a user or group. Open the database in FileMaker Pro and choose Manage Security from the File menu. On top of the dialog you'll find a dropdown named "Authenticate via" - select the option Claris ID. Navigate to the advanced settings. In the register "Extended Privileges", you'll find an entry fmrest ("Access via FileMaker Data API"). Add this special right to a "Privilege Set". Assign the set to the user or group.

![image](https://user-images.githubusercontent.com/1469531/182467698-7ec525f9-5668-42bb-aca8-cec1445ee747.png)

![image](https://user-images.githubusercontent.com/1469531/182467743-89eca7e9-1f26-4869-92ff-83977d671cb4.png)


## Instantiate the client
We can use the FileMakerRestClient, when the setup is done.
Just create a new ConnectionInfo object and set the required properties:
```
    var conn = new ConnectionInfo();
    conn.FmsUri = "https://{NAME}.account.filemaker-cloud.com";
    conn.Username = "user@domain.com";
    conn.Password = "********";
    conn.Database = "Reporting";
```
Then instantiate the FileMakerRestClient with a FileMakerCloudAuthTokenProvider as follows:

```
    var fm = new FileMakerRestClient(new HttpClient(), new FileMakerCloudAuthTokenProvider(conn));
```

From here you can use the client according to the given samples in the readme.
You can also check, wether the authentication was successfull:

```
    await fm.RefreshTokenAsync();
    Assert.True(fm.IsAuthenticated);
```
  
## Note
AWS Cognito is used as Identity provider. You can find more information [here](https://help.claris.com/en/customer-console-help/content/create-fmid-token.html).
You'll find the following preconfigured properties in the ConnectionInfo object:
- RegionEndpoint (Region)
- CognitoUserPoolID (UserPool_ID)
- CognitoClientID (Client_ID)

**Comment by fuzzzerd** [comment]
Thank you @heebinho, this is fantastic!
