### ISSUE TITLE
ProtocolViolationException when using method GetByFileMakerIdAsync

### ISSUE THREAD

**Issue by zandhaai** [fuzzzerd/fmdata#259]
# Describe the bug

I am testing your library and noticed if I want to fetch a record by an id and using method 'GetByFileMakerIdAsync' I am getting this 'ProtocolViolationException' (Cannot send a content-body with this verb-type) in 'System.Net.HttpWebRequest.CheckProtocol(Boolean onRequestStream)'.

I noticed the following content is being set while in method 'ExecuteRequestAsync' for the Get Request:

{"query":[],"limit":"100","offset":"1"}

It seems this is not allowed when doing GET requests.

## FMData version

Nuget Package 5.0.0

## Proposed Solution

I have added the following 'hackish' solution to a local copy of your project:
```
if (method != HttpMethod.Get) 
{    
    httpRequest.Content = httpContent; 
}
```

**Comment by fuzzzerd** [comment]
@zandhaai would you be willing to submit a PR with the suggested change?

**Comment by zandhaai** [comment]
Yes, sure!
