### ISSUE TITLE
JsonReader Exception on valid JSON (Unexpected character encountered)

### ISSUE THREAD

**Issue by peterkd** [fuzzzerd/fmdata#28]
Hello,

This is a very handy library.

I'm getting the JsonReaderException: Unexpected character encountered while parsing value: [. 

I wonder whether the it's trying to parse an encoded response. I don't see any invalid characters in the JSON itself...

Thanks,

Peter

**Comment by fuzzzerd** [comment]
Can you provide more details on where the failure occurred and a stack trace?
