### ISSUE TITLE
Get Specific Layout missing result Property

### ISSUE THREAD

**Issue by Kevin060901** [fuzzzerd/fmdata#321]
# Describe the bug
In the fieldMetaData portion of the layoutmetadata is a property "result" which is missing in the FieldMetadata class.

```json
{
  "response": {
    "fieldMetaData": [
      {
        "name": "CustomerName",
        "type": "normal",
        "displayType": "editText",
        "result": "text",
        "valueList": "Text",
        "global": false,
        "autoEnter": false,
        "fourDigitYear": false,
        "maxRepeat": 1,
        "maxCharacters": 0,
        "notEmpty": false,
        "numeric": false,
        "timeOfDay": false,
        "repetitionStart": 1,
        "repetitionEnd": 1
      }
    ],
    "portalMetaData": {},
    "valueLists": [
      {
        "name": "Region",
        "type": "customList",
        "values": [
          {
            "displayValue": "West",
            "value": "West"
          }
          , 
          {
            "displayValue": "East",
            "value": "East"
          }
        ]
      }
    ]
  },
  "messages": [
    {
      "code": "0",
      "message": "OK"
    }
  ]
}
```

## Steps To Reproduce

Request any LayoutMetadata

## Expected behavior

There should be a property in the FieldMetadata class representing the result as its the only way to know which datatype is expected in that field.

## fmdata version

v5.1.1

**Comment by fuzzzerd** [comment]
I will try to take a look this week. @Kevin060901, if you want to submit a pull in the mean time, that'd be fantastic.

**Comment by fuzzzerd** [comment]
@Kevin060901 a fix for this has been released: https://github.com/fuzzzerd/fmdata/releases/tag/v5.1.2.
