### ISSUE TITLE
Nested array filtering

### ISSUE THREAD

**Issue by peterkd** [fuzzzerd/fmdata#54]
The find API call returns nested array - as in the example below (NestedActions).

I would like apply the following query: get all records that have fielddata.ES_UTC_Time >= 63397939255000 and apply the same date filter against the NestedActions::ES_UTC_Time.

{"query":[{"ES_UTC_Time":">= 63397939255000"},{"NestedActions::ES_UTC_Time":">= 63397939255000"}],"offset":"1", "limit":"100","sort":[{"fieldName":"ES_UTC_Time","sortOrder":"descend"}]}

I would like to return the parent record even if there are no child NestedActions.

Is this even possible when using the FM API find call ? How would I need to structure the fmdata filter to achieve this?

Appreciate a any help with this.

Thanks.

Data:
{
    "response": {
        "data": [
            {
                "fieldData": {
                    "ES_RECORD_ID": 5.1424603688874037043940639545611105393e+37,
                    "ES_UTC_Time": 63677801587705
                },
                "portalData": {
                    "NestedActions": [
                        {
                            "recordId": "26",
                            "NestedActions::ES_UTC_Time": 63675911309428,
                            "NestedActions::ES_RECORD_ID": 3.58945963486201731120694061631247244196e+38,
                            "modId": "0"
                        },
                        {
                            "recordId": "27",
                            "NestedActions::ES_UTC_Time": 63677800967265,
                            "NestedActions::ES_RECORD_ID": 4.11367583929358143594030872930602025971e+38,
                            "modId": "0"
                        }
                    ],
                    "FormBeforeEventTimeline": [],
                    "FormAfterEventTimeline": []
                },
                "recordId": "46",
                "modId": "12"
            },
            {
                "fieldData": {
                    "ES_RECORD_ID": 2.32825376899054305232124784142823827507e+38,
                    "ES_UTC_Time": 63675551352139
                },
                "portalData": {
                    "NestedActions": [],
                    "FormBeforeEventTimeline": [],
                    "FormAfterEventTimeline": []
                },
                "recordId": "45",
                "modId": "15"
            }
        ]
    },
    "messages": [
        {
            "code": "0",
            "message": "OK"
        }
    ]
}

**Comment by fuzzzerd** [comment]
It seems like you might need two find requests to achieve this. One to find all of the records matching the parent criteria with no portal rows and then a second one that finds matching parent and portal rows.

Currently the strongly typed methods don't have that ability, however, if you manually build up the `FindRequest<T>` object you can add as many instances to the `.Query` property as you want. Each of those will represent something analogous to a new find request in filemaker pro.

**Comment by peterkd** [comment]
Thanks. I initially thought about sending two requests but since FileMaker applies the collection of conditions as OR statements, that functionality fulfilled my requirement.

I manually built up the query filter and it worked without issues.

Thanks !

**Comment by fuzzzerd** [comment]
No problem. Glad that worked out!
