### ISSUE TITLE
Perform find request doest no work

### ISSUE THREAD

**Issue by korpinz** [fuzzzerd/fmdata#55]
Hello, 

Maybe I'm wrong in running the code but I have a class "Members" that has more than 20 fields and I run client.FindAsync (toFind) I always have an error.

Indeed, toFind contains my class (with string and int) and sends the complete class.

I feel like this perform find is trying to find a record in Filemaker that has exactly the same values than my class and not just "Member_Zkp_WEB".
The problem is that my class model contains some var who doesnt exist in Filemaker. But it looks like it tries to perform the find on the whole class skeleton.

If comment almost all my vars in my class and i only let Member_Zkp_Web and for example Member_LastName the perform find works en results is giving me the correct record it found.

ViewBag.sessionv contains 26, which exist on my layout.

```
                FileMakerRestClient client = new FileMakerRestClient("https://fms171.hostmy.solutions", "helloJAK", userName, password);
                var toFind = new Models.Members { Member_Zkp_WEB = ViewBag.sessionv };
                var results = await client.FindAsync(toFind);

```

**Comment by fuzzzerd** [comment]
Your assertion is correct. The instance of a class that is passed to `.FindAsync` will use any non-null, non-default value properties generate the find request. 

If you have fields that you need on the model for one reason or another but do not have them included on the FileMaker layout, you can use `[NotMapped]` or `[JsonIgnore]` on those properties to ensure they are not mapped by JSON.NET and passed along to the Data API.

An alternate approach would be to create a model that matches your layout exactly and then use a tool like AutoMapper to map the response from FMData to your domain model. This is the way I primarily consume data from the Data API, but it depends on your use case and what makes more sense.

**Comment by korpinz** [comment]
Thanks for answering!

The problem is i need the value back.

Actually i want to find a record only by a key (Member_Zkp_Web) and to receive all the datas from Filemaker fields on the layout.

I think the problem is because i've some bool in my model and i have to convert it to Int32.

**Comment by fuzzzerd** [comment]
In your case you probably want to create a model specifically for querying and then use AutoMapper to map between that class and your existing class. That way you can define the bools as ints (since filemaker doesn't have a boolean type) and then in the AutoMapper config you can manage the int <=> bool conversion.
