### ISSUE TITLE
ContainerData : Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by korpinz** [fuzzzerd/fmdata#59]
Hey,

I'm trying to use the ContainerData but i always receive an error which is "Object reference not set to an instance of an object.".
My container contains a picture on my layout and in my model i've created a byte[] to receive it.

```
        [ContainerDataFor("Picture_gr")] // use the name in your C# model
        public byte[] Member_Picture { get; set; }

```
Maybe i'm doing something wrong but there is only 4 lines of code...

```
                FileMakerRestClient client = new FileMakerRestClient(serverName, fileName, userName, password);
                var toFind = new Models.Members { Member_Zkp_WEB = ViewBag.sessionv };
                var results = await client.FindAsync(toFind);
                await client.ProcessContainers(results);
```

Did you know about this error? Maybe you know a workaround or how to fix it?

Thx in advance!

Korp

**Comment by fuzzzerd** [comment]
Your four consumer lines look good, I suspect a problem in your model. Perhaps the documentation could be more clear.

You need two properties on your model for container data. You need a string that maps to the container field and you need a byte array with the attribute.

```csharp
[DataMember]
public string ContainerField { get; set; }
[ContainerDataFor("ContainerField")]
public byte[] ContainerData { get; set; }
```

**Comment by korpinz** [comment]
Yep thanks, i missed the string part! Now it works. To update or create a record who contains a container (image) do i need to do someting in particular?
